postBuild

Fixed issue 1

---

experiments/getting_started_with_notebooks.ipynb

added topics, deleted the part dedicated to python

changed everything in the notebook

---

docs/conf.py
docs/environment.yml

We don't need all the packages, so this will greatly improve the websites build speed and stability

Simplify doc environment on ReadTheDocs

---

notebooks/oggm-tuto/inversion_with_frontal_ablation.ipynb

We worked on it with @bearecinos

Add a notebook about frontal ablation

---

notebooks/oggm-tuto/area_length_filter.ipynb
notebooks/oggm-tuto/deal_with_errors.ipynb
notebooks/oggm-tuto/getting_started.ipynb
notebooks/oggm-tuto/inversion.ipynb
notebooks/oggm-tuto/inversion_with_frontal_ablation.ipynb
notebooks/oggm-tuto/preprocessing_errors.ipynb
notebooks/oggm-tuto/welcome.ipynb

add tutorials together with recent doc upgrades

add tutorials

---

notebooks/oggm-edu/surging_experiment.ipynb

For some reason it didn't work properly

Remove ipywidget cell

---

notebooks/oggm-tuto/alternative_dem.ipynb

closes https://github.com/OGGM/oggm-edu/issues/39

Add a DEM example

---

notebooks/oggm-tuto/alternative_dem.ipynb

This removes the tandem-x example as one needs SSH entry to the cluster to get them

Remove TanDEM-X example

---

notebooks/oggm-tuto/merging_glaciers.ipynb
notebooks/oggm-tuto/welcome.ipynb

This adds one notebook as a tutorial how to use the merging glacier tasks.
It also notes some limitations of the method and applicability.

Tutorial for merging glaciers

---

notebooks/oggm-tuto/merging_glaciers.ipynb

mini changes cc @matthiasdusch

Small changes in merged glaciers tutorial

---

notebooks/oggm-tuto/massbalance-calibration.ipynb

Companion to this pr: https://github.com/OGGM/oggm/pull/741
cc @peltoglacier

Add a tutorial for the mass-balance calibration

---

notebooks/oggm-tuto/pyviz_intro.ipynb
notebooks/oggm-tuto/welcome.ipynb

preparation for tomorrow's workshop

add pyviz tutorial

---

docs/index.rst
docs/roadmap.rst

Follow up on dicsussion with @zschirmeister @dfrisinghelli @pat-schmitt @ehultee 
It's only partly written, but it's Friday so I stopped ;-)

Add draft roadmap

---

docs/conf.py
docs/gallery.rst

Repair badges and brake singe lines

---

docs/simulator.rst

Here is an example for an experiment. What do you think?

added experiment for glacier slope

---

docs/simulator.rst

Update simulator version

---

oggm_edu/funcs.py

- added patricks new function for EarthCUBE
- added a function to plot png besides a normal plot
- changed some stuff in intro_glacier_plot

improve glacier advance and retreat notebook and EarthCube2021

---

docs/simulator.rst

Changed BOKEH_ALLOW_WS_ORIGIN and the address to start the app in the browser

Update docker comment

---

docs/simulator.rst

changed "wider top" to "Wide top, narrow bottom" in simulator "Glacier Shape" experiment

Small renaming

---

docs/conf.py
docs/environment.yml
docs/index.rst
docs/mb_simulator.rst
docs/simulator.rst

Small additional changes and theme update

---

docs/glacier_debriscovered.rst
docs/index.rst

Adding the debris-covered glacier graphics of @linznicholson.
Before this pull request is merged first pull request https://github.com/OGGM/glacier-graphics/pull/2 should be merged, afterwards, I can check if the links to the graphics used here are working.

add debris-covered glacier graphic

---

oggm_edu/glacier.py
oggm_edu/glacier_collection.py

- Adds max ice thickness and type to representation of `Glacier`, `SurgingGlacier` and `GlacierCollection`.
- `GlacierCollection.plot`: Info boxes also show type of each glacier.
- `Glacier.plot` now display the ELA in the top down view when there is no ice.
Closes #137

Representation and small plot updates.

---

oggm_edu/glacier.py
oggm_edu/glacier_bed.py
oggm_edu/glacier_collection.py
oggm_edu/mass_balance.py
oggm_edu/tests/test_glacier.py
oggm_edu/tests/test_glacier_collection.py

Introduces some changes and new functionality.
- Plot updates: 
- No longer add a fixed 2km to the end of all glaciers. Instead we add 2% of total bed length. Fixed 2km looked bad on shorter beds.
- Moved ELA annotation to RHS in `plot_state_history`
- `plot_state_history` no longer fail when there is no `state_history`.
- Changes in logic for the case when glacier outgrow domain. Before we raised an error. This caused issues with `GlacierCollection.progress..`.  If one glacier outgrew domain, progression stopped for all glaciers. This is no longer the case.
- `GlacierCollection` now performs progressions in parallel, depending on the nr of available processors. Maybe not super necessary.  But fun!
- Added a check if there is a non-complete temperature bias scenario before adding a new …

Various quality improvements

---

.gitignore
docs/api.rst
docs/conf.py
docs/environment.yml
oggm_edu/glacier.py
oggm_edu/glacier_bed.py
oggm_edu/glacier_collection.py
oggm_edu/mass_balance.py

@Holmgren825 as I was documenting a few more things I noticed that `GlacierCollection`was still referring to `glacier.current_state` although your previous PR made it private. I corrected this in `GlacierCollection` but I think that if you need this attr outside the class it should not be private

Add examples to doc and fix problem with previous version

---

docs/environment.yml

The build and tests work with OGGM minimal

Simplify build

---

oggm_edu/glacier.py
oggm_edu/glacier_bed.py
oggm_edu/glacier_collection.py
oggm_edu/mass_balance.py
oggm_edu/tests/test_glacier.py
oggm_edu/tests/test_mass_balance.py

This PR introduces a new way for the mass balance to handle changes in the temperature bias (or ELA changes). This is now done via the new attribute `MassBalance.temp_bias_series` which hold the historical and possible future values of the temperature bias of the mass balance. Future values are added to this series through either the methods `add_temp_bias` or `add_random_climate`. It is also possible for the user to assign a completely custom temperature bias series to the attribute. The mass balance model then reads from this series during runtime. This has the added benefit that it greatly simplifies `Glacier.run_to...` methods.
This also includes ways to visualise the `temp_bias_series` via `plot_history` via the `show_bias` argument. It is also possible to smooth the bias data for …

New mass balance customisation interface and other qol updates.

---

oggm_edu/funcs.py
oggm_edu/glacier.py
oggm_edu/glacier_bed.py
oggm_edu/tests/test_glacier_bed.py

This PR includes
- Warnings when user sets bad values for some parameters. Closes https://github.com/OGGM/oggm-edu-notebooks/issues/71
- AAR to glacier info. Closes https://github.com/OGGM/oggm-edu-notebooks/issues/62
- Enables the user to pass a temperature when setting the creep parameter A in Glens equation. The temperature is then converted to a creep parameter according to eq. 3.35 in The physics of glaciers, Cuffey & Paterson. See discussion in the issue.  Closes https://github.com/OGGM/oggm-edu-notebooks/issues/72

Glens A, warnings and outputs

---

docs/gallery.rst

Demonstrate how to use the Glacier Gallery in teaching with link to SERC activity

Add link to OGGM-Edu Lab 1

---

docs/explorer.rst

Wording change in 'Questions to explore' preface.  Link to OGGM-Edu Lab 2 to show how to use this app in the classroom.

Refocus explorer.rst on instructors

---

docs/explorer.rst

Add the stable branch to MyBinder link and docker comment.

Use stable branch for explorer

---

oggm_edu/__init__.py
oggm_edu/funcs.py
oggm_edu/glacier.py
oggm_edu/glacier_bed.py
oggm_edu/glacier_collection.py
oggm_edu/tests/test_glacier_collection.py

A mpl bugfix, some minimal internal changes, and a new `plot_side_by_side` method for GlacierCollection

Some updates to oggm-edu package

---

docs/api_detailed.rst
oggm_edu/glacier.py
oggm_edu/glacier_collection.py
oggm_edu/mass_balance.py
oggm_edu/tests/test_glacier_collection.py

Closes https://github.com/OGGM/oggm-edu-notebooks/issues/74

More enhancements!

---

docs/simulator.rst

Here I have updated the docker image for the simulator to work with the SemiImplicitModel.

updated docker image for simulator

---

oggm_edu/glacier.py
oggm_edu/glacier_collection.py

This adds a new id attribute to glaciers. By default this is set to a random 5 character sequence but can be specified at init.
Also corrected some spelling mistakes.
Closes #187

New id attribute for glaciers

---

docs/index.rst

I'm just using this as an example to show how to make a PR :)

remove link to twitter
